### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by KamalAman** [olup/react-hook-mousetrap#1]
Hi loup,

Reviewed your code here and there are a few bugs I noticed and a few api changes would resolve those bugs:

**Suggestion 1**: Api Example
Right now your api is `mousetrapHook(<Array>(handler<object>))`

Hooks should start with `use<Name>` which allows react's linter to kick in to prevent misuse of the hook.

```javascript
 useMousetrap(<Array>(handler<object>))
```

**Suggestion 2**: Handle key and actions changes and simplify logic
If your actions or key changes, your hook will not properly update since the first useEffect does not have any variable dependences. Also, having hook depend on arrays is difficult to deal with this challenge. Finally there is no reason to use useState in your hook.

Change your api to  
```javascript
 useMousetrap(<string>key, <fn>action)
```

And your hook to 

```javascript
export default function useMousetrap = (key, action) => {

  useEffect(() => {
    mousetrap.bind(keys, action);
    return () =>  mousetrap.unbind(keys);
  }, [key, action]);
}
```

The one caveat with any hook is that objects need to be memoized properly otherwise updates to useEffect will constantly change.

The the example should utilize reacts's useCallback

```javascript
const onCtrlEnter = useCallback(() => {
  
});
useMousetrap("ctrl+enter", onCtrlEnter);

const onCtrlX = useCallback(() => {
  
}) 
useMousetrap("ctrl+x", onCtrlX);
```

**Comment by olup** [comment]
Thanks for the input ! I'll update that accordingly.


I agree with naming convention, and with the use of a single hook for every
hotkey call back to register, which could make more sense.


But my main challenge was this : imagine you have a call back that uses a
state ever changing, like the text you are typing, I do not want to
register and unregister mousetrap at every keystroke. This is exactly why I
use a state hook, so that I can have an effect hook that is trigger once at
mount and will clean only at unmount. In turn, it will call a dynamic call
back, that is updated every time it's parameters changes. I'll look into
what useCallback memoisation can do for me (I actually did not know this
one).

Any advice on my use case ?

Le lun. 4 févr. 2019 à 02:46, Kamal Aman <notifications@github.com> a
écrit :

**Comment by KamalAman** [comment]
If you expect the dependencies of the action to change frequently, you can `useRef` to skip binding and unbinding when the action changes.

```javascript
import { useEffect, useRef } from 'react';

export default function useMousetrap = (key, action) => {
  let actionRef = useRef(null);
  actionRef.current = action;

  useEffect(() => {
    mousetrap.bind(keys, (...args) => {
       if (!actionRef.current) return;
       actionRef.current(...args)
     });
    return () =>  mousetrap.unbind(keys);
  }, [key]);
}
```


This way, you can change the action frequently and skip binding and unbinding every time.

This way, there really isn't a need to use `useCallback` in the example since the latest action will always be referenced.

There is still no need for a `useState`

**Comment by olup** [comment]
Yeah, i thought useRef in this case was not advised, but, going back to the doc I don't see why, so i'll use it.
